import {
  Soup, Salad, Fish, Beef, CakeSlice, Coffee, Wine, Cookie,
  Sandwich, IceCream2, Beer, Flame, Leaf, Egg, Croissant,
  ChefHat, Pizza, Drumstick, Apple, Star, UtensilsCrossed,
  type LucideIcon,
} from "lucide-react"

const ICON_MAP: Record<string, LucideIcon> = {
  entradas: Soup,
  entrada: Soup,
  sopas: Soup,
  sopa: Soup,
  petiscos: UtensilsCrossed,
  snacks: Cookie,
  saladas: Salad,
  salada: Salad,
  vegetariano: Leaf,
  vegano: Leaf,
  "pratos principais": Beef,
  "prato principal": Beef,
  pratos: UtensilsCrossed,
  peixe: Fish,
  peixes: Fish,
  mariscos: Fish,
  marisco: Fish,
  frutos_do_mar: Fish,
  carnes: Beef,
  carne: Beef,
  grelhados: Flame,
  churrasco: Flame,
  grelhado: Flame,
  frango: Drumstick,
  aves: Drumstick,
  "sanduíches": Sandwich,
  sanduiche: Sandwich,
  "hambúrgueres": Sandwich,
  hamburguer: Sandwich,
  burgers: Sandwich,
  pizzas: Pizza,
  pizza: Pizza,
  sobremesas: CakeSlice,
  sobremesa: CakeSlice,
  doces: Cookie,
  pastelaria: Croissant,
  gelados: IceCream2,
  gelado: IceCream2,
  sorvetes: IceCream2,
  bebidas: Coffee,
  bebida: Coffee,
  drinks: Coffee,
  sumos: Apple,
  sumo: Apple,
  vinhos: Wine,
  vinho: Wine,
  cervejas: Beer,
  cerveja: Beer,
  cocktails: Wine,
  "pequeno almoço": Croissant,
  "café da manhã": Croissant,
  brunch: Egg,
  especiais: Star,
  especial: Star,
  "pratos do dia": ChefHat,
  "prato do dia": ChefHat,
  "sugestões": ChefHat,
  "sugestão": ChefHat,
}

export function getCategoryIcon(name: string): LucideIcon {
  return ICON_MAP[name.toLowerCase().trim()] ?? UtensilsCrossed
}
